{{- if .Values.podMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: {{ template "certificator.name" . }}
    release: {{ .Release.Name }}
    nais.io/prometheus: "nais"
  name: {{ template "certificator.name" . }}
spec:
  jobLabel: app.kubernetes.io/name
  podMetricsEndpoints:
  - path: /metrics
    port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "certificator.name" . }}
{{- end }}
