kind: ServiceAccount
apiVersion: v1
metadata:
  labels:
    {{- include "certificator.labels" . | nindent 4 }}
  name: {{ include "certificator.fullname" . }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "certificator.labels" . | nindent 4 }}
  name: {{ include "certificator.fullname" . }}
rules:
  - apiGroups:
    - "*"
    resources:
    - "configmaps"
    verbs:
    - get
    - list
    - create
    - update
    - watch
  - apiGroups:
    - "*"
    resources:
    - "namespaces"
    verbs:
    - get
    - list
    - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "certificator.labels" . | nindent 4 }}
  name: {{ include "certificator.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "certificator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "certificator.fullname" . }}
  namespace: "{{ .Release.Namespace }}"
