name: Build and deploy image
on:
  push:
    branches: master
    paths-ignore:
      - "charts/**"
      - "*.md"
jobs:
  build_and_push:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    outputs:
      "version": ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # ratchet:actions/checkout@v3
      - name: Generate version
        id: version
        run: echo "version=$(date +'%Y%m%d-%H%M%S')-$(git rev-parse --short HEAD)" >> ${GITHUB_OUTPUT}
      - uses: nais/platform-build-push-sign@a31c0ad7e31ff154df50baa9c3a5d33b310e8209 # ratchet:nais/platform-build-push-sign@main
        id: build-push-sign
        with:
          name: certificator
          google_service_account: gh-certificator
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          push: true
  rollout:
    permissions:
      id-token: write
    needs: ["build_and_push"]
    runs-on: fasit-deploy
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: nais/fasit-deploy@b2c0b6d049b53bef41b321eec406fe66938576fd # ratchet:nais/fasit-deploy@main
        with:
          json: '{"image": {"tag": "${{ needs.build_and_push.outputs.version }}"}}'
          feature_name: certificator
